# Cyberpunk Theme - Neon City Nights
# Inspired by Cyberpunk 2077, Blade Runner, and neon-lit cityscapes
# Hot pink, electric cyan, toxic yellow on deep dark backgrounds

name = "cyberpunk"
description = "Neon-drenched cyberpunk aesthetic with hot pinks and electric blues"
author = "Zush"
version = "1.0.0"

[colors]
bg_dark = "#0a0a0f"
bg_segment = "#12121a"
neon_pink = "#ff2a6d"
neon_cyan = "#05d9e8"
neon_yellow = "#f9f002"
neon_purple = "#d300c5"
neon_orange = "#ff6e27"
chrome = "#c0c0c0"
dark_chrome = "#404040"
glitch_red = "#ff0055"
glitch_green = "#00ff9f"
fg_dark = "#0a0a0f"
white = "#ffffff"

[symbols]
# Sharp slant separators for edgy cyberpunk look
sep_slant = "\ue0b8"
sep_slant_left = "\ue0ba"

# Icons
prompt_arrow = "⟫"
git_icon = ""
lambda = "λ"
folder = ""
tri_left = "◢"
tri_right = "◣"

[templates]
main = """\
(fg bg_segment)@sep_slant_left(/fg)\
(bg bg_segment)(fg neon_cyan) @tri_left (/fg)(fg neon_pink)(b){{time}}(/b)(/fg)(fg neon_cyan) @tri_right (/fg)(/bg)\
(bg neon_pink)(fg bg_segment)@sep_slant(/fg)(/bg)\
(bg neon_pink)(fg fg_dark) @lambda (/fg)(/bg)\
(bg neon_cyan)(fg neon_pink)@sep_slant(/fg)(/bg)\
(bg neon_cyan)(fg fg_dark) @folder {{pwd_short}} (/fg)(/bg)\
{{#if git_branch}}\
(bg neon_purple)(fg neon_cyan)@sep_slant(/fg)(/bg)\
(bg neon_purple)(fg white) @git_icon {{git_branch}}{{#if (gt git_modified 0)}} (fg neon_yellow)✦{{git_modified}}(/fg){{/if}}{{#if (gt git_staged 0)}} (fg glitch_green)+{{git_staged}}(/fg){{/if}}{{#if (gt git_untracked 0)}} (fg chrome)?{{git_untracked}}(/fg){{/if}} (/fg)(/bg)\
(fg neon_purple)@sep_slant(/fg)\
{{else}}\
(fg neon_cyan)@sep_slant(/fg)\
{{/if}}
(fg dark_chrome)▰▰(/fg)
{{#if (eq exit_code 0)}}(fg neon_cyan)⟫(/fg)(fg neon_pink)⟫(/fg)(fg neon_yellow)⟫(/fg) {{else}}(fg glitch_red)⟪{{exit_code}}⟫ ⟫⟫⟫(/fg) {{/if}}"""

transient = """(fg dark_chrome){{time}}(/fg) {{#if (eq exit_code 0)}}(fg dark_chrome)⟫(/fg) {{else}}(fg glitch_red)⟫(/fg) {{/if}}"""

right = ""
