# Remote SSH Theme
# Colorful powerline prompt designed for remote/SSH sessions
# Highly visible colors to distinguish remote from local terminals

name = "remote"
description = "Colorful powerline theme for SSH/remote sessions"
author = "Zush"
version = "1.0.0"

[colors]
pink = "#e26e88"
coral = "#f2a272"
teal = "#67d4c4"
green = "#7eca9c"
yellow = "#ebc275"
orange = "#f2994a"
blue = "#6bb8d9"
purple = "#b48ead"
red = "#f38ba8"
dark = "#1a1b26"
darker = "#11111b"
light = "#cdd6f4"
dimmed = "#6c7086"
ssh_bg = "#9d4edd"
ssh_fg = "#ffffff"

[symbols]
sep = ""
sep_thin = ""
pill_left = ""
pill_right = ""
ssh = "󰣀"
folder = ""
git_branch = ""
clock = ""
user_icon = ""
server = "󰒋"

[templates]
left = """{{#if is_ssh}}(fg #9d4edd)(sym inverted_triangle_left)(/fg)(bg #9d4edd)(fg #ffffff)(bold) 󰣀 (/bold)(/fg)(/bg)(bg #e26e88)(fg #9d4edd)(/fg){{else}}(fg #e26e88)(/fg)(bg #e26e88){{/if}}(fg #1a1b26)(bold) {{user}}{{#if is_ssh}}@{{host}}{{/if}} (/bold)(/fg)(/bg)(bg #f2a272)(fg #e26e88)(/fg)(fg #1a1b26)(bold)  {{pwd_short}} (/bold)(/fg)(/bg){{#if git_branch}}(bg #67d4c4)(fg #f2a272)(/fg)(fg #1a1b26)(bold)  {{git_branch}}(/bold){{#if (gt git_staged 0)}} (fg #1a1b26)+{{git_staged}}(/fg){{/if}}{{#if (gt git_modified 0)}} (fg #ebc275)!{{git_modified}}(/fg){{/if}}{{#if (gt git_untracked 0)}} (fg #f38ba8)?{{git_untracked}}(/fg){{/if}}{{#if (gt git_deleted 0)}} (fg #f38ba8)-{{git_deleted}}(/fg){{/if}} (/fg)(/bg)(bg #6bb8d9)(fg #67d4c4)(/fg){{else}}(bg #6bb8d9)(fg #f2a272)(/fg){{/if}}(fg #1a1b26)(bold)  {{time}} (/bold)(/fg)(/bg)(fg #6bb8d9) (/fg)"""

right = """"""

main = """{{first_line}}
{{#if (eq exit_code 0)}}(fg #7eca9c)(bold)❯(/bold)(/fg) {{else}}(fg #f38ba8)(bold)[{{exit_code}}] ❯(/bold)(/fg) {{/if}}"""

transient = """{{#if is_ssh}}(fg #9d4edd)󰣀(/fg) {{/if}}{{#if (eq exit_code 0)}}(fg #7eca9c)❯(/fg) {{else}}(fg #f38ba8)❯(/fg) {{/if}}"""
